version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: nestjs-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: nestjs_boilerplate

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-backend
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
