export const DEFAULT_DEPARTMENTS = [
  {
    name: 'Garbage / Waste Management Department',
    responsibility: [
      'Collection of household waste.',
      'Collection of commercial waste.',
      'Removal of garbage from public places.',
      'Street sweeping and cleanliness.',
      'Cleaning of garbage bins and dumpsters.',
      'Waste segregation and recycling.',
      'Disposal of solid waste.',
      'Removal of illegal dumping.',
      'Management of landfill sites.',
      'Cleaning of drains blocked by garbage.',
      'Collection of hazardous household waste.',
      'Public sanitation and cleanliness initiatives.',
    ],
  },
  {
    name: 'Industry Department',
    responsibility: [
      'Industrial licensing and permits.',
      'Factory operations compliance.',
      'Industrial pollution control.',
      'Manufacturing facility regulation.',
      'Workplace safety compliance.',
      'Industrial infrastructure support.',
      'Environmental compliance for industries.',
      'Industrial development projects.',
      'Industrial land allocation.',
      'Industrial zone management.',
      'Factory inspections.',
      'Industrial waste generated by factories.',
      'Labor law compliance in industries.',
      'Industrial utility services.',
    ],
  },
];

export const SUCCESS_MSG = {
  SEED: 'departmentSuccess.SEED',
  ALREADY_EXISTS: 'departmentSuccess.ALREADY_EXISTS',
};
