export enum SmsErrorCode {
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  INVALID_PHONE = 'INVALID_PHONE',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  RATE_LIMITED = 'RATE_LIMITED',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
}
